n_episodes: 2000  # Total episodes to achieve
max_t: 1000       # Number of actions per episode
eps_start: 1.0    # Epsilon start
eps_end: 0.01     # Epsilon min value
eps_decay: 0.995  # Epsilon decay